services:

  db:
    image: postgres:16-alpine
    container_name: passwordmanager-db
    restart: always
    environment:
      POSTGRES_USER: PasswordManager
      POSTGRES_PASSWORD: passMan
      POSTGRES_DB: PasswordManagerDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U PasswordManager -d PasswordManagerDB"]
      interval: 5s
      retries: 5

  app:
    build: .
    container_name: passwordmanager-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DATABASE_URL: postgresql://PasswordManager:passMan@db:5432/PasswordManagerDB?schema=public
      JWT_SECRET: kasAAfq%A%DEaksdASAsdanJnDaJDnkNASdkJANSDRjkNASDJASNLKkasjdnsakdjnadkLASDQweGRfbilAHJDSL!:BKUV..,LIbfweli%binABLFFDI%BADbwjfbwifbwfbw
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: